export const agmPoster = {
  title: 'Architecture Graph Method (AGM)',
  subtitle: 'Auf einer Seite',
  thesis: 'Architekturdokumentation ist die API der KI-Konversation.',
  tagline:
    'Repo-lokaler Markdown-Linkgraph unter docs/architecture/, orchestriert über blueprint.md, gepflegt durch KI-Agenten mit menschlicher Validierung.',
  goldenPath: [
    { step: 'Install', action: 'Scaffold im App-Repo', workflow: 'agm-install.sh / agm install' },
    { step: 'Adopt', action: 'Erste evidenzbasierte Sektion', workflow: 'bootstrap-adopt' },
    { step: 'Continue', action: 'Nächstes Kapitel aus blueprint.md', workflow: 'bootstrap-continue' },
    { step: 'Maintain', action: 'Docs mit Code synchronisieren', workflow: 'maintenance-diff-range' },
    { step: 'Review', action: 'Report-only — frischer Chat', workflow: 'review-maintenance' },
  ],
  tracks: [
    { name: 'Build', role: 'role-bootstrap.md', prefix: 'bootstrap-*', purpose: 'Install, Adopt, Kapitel aufbauen' },
    { name: 'Evolve', role: 'role-maintenance.md', prefix: 'refinement, maintenance*', purpose: 'Vertiefen, Sync bei git diff' },
    { name: 'Architect', role: 'role-architecture-work.md', prefix: 'architecture-work-*', purpose: 'Fragen, Analysen, Designs' },
    { name: 'Domain', role: 'role-domain-work.md', prefix: 'domain-work-*', purpose: 'DDD, Context Map, Tactical Review' },
    { name: 'Verify', role: 'role-review.md', prefix: 'review-*', purpose: 'Qualität — immer neuer Chat' },
  ],
  orchestration: [
    { file: 'context/always-on.md', role: 'Jede Session: Identität, Stack, Source Map' },
    { file: 'blueprint.md', role: 'Bauplan: Phasen, WRK, Session-Log — kein Fließtext' },
    { file: 'entry-point.md', role: 'Agent-Navigation: nur Links, kein Status' },
    { file: 'index.md + log.md', role: 'OKF: progressive disclosure + Änderungslog' },
  ],
  okf: [
    'Markdown + YAML-Frontmatter — Pflichtfeld: type',
    'index.md = OKF-Index · entry-point.md = Agent-Navigation — nie vermischen',
    'log.md = append-only Change Log pro Ebene',
    'Konform mit Google Open Knowledge Format v0.1',
    'Git-native: PR, Diff, Review, CI-Link-Check',
  ],
  principles: [
    { n: 1, title: 'Deterministische Traversierung', text: 'Explizite Markdown-Links — keine Ähnlichkeitssuche, keine Halluzinations-Chunks' },
    { n: 2, title: 'Dokumentation als Code', text: 'Graph im Repo — PR ändert Docs mit Code, Git-History gilt' },
    { n: 3, title: 'KI-gepflegter Lebenszyklus', text: 'Bootstrap · Refinement · Maintenance · Architecture Work · Review' },
    { n: 4, title: 'Session-Kontinuität', text: 'blueprint.md = persistenter Architektur-Backlog über Sessions' },
    { n: 5, title: 'Schnittstellenverträge', text: 'exports.md (was die App liefert) · imports.md (Links zu Partnern)' },
    { n: 6, title: 'Architektur-Guardrails', text: 'Smells, SOLID, Stil — Findings in blueprint.md, Entscheidungen als ADR' },
    { n: 7, title: 'Referenzielle Integrität', text: 'LINK_CHECK vor Output · CI agm-integrity' },
  ],
  compare: {
    traditional: [
      'Repo / Chat-Verlauf einfügen',
      'RAG / Ähnlichkeitssuche',
      'Stale Wiki / Confluence',
      'Schreiben + Review im selben Chat',
    ],
    agm: [
      'always-on.md + blueprint.md lesen',
      'Links von entry-point.md folgen',
      'git diff → maintenance-diff-range',
      'Verify immer in frischem Chat',
    ],
  },
  phaseStates: [
    { state: '[ ]', label: 'offen' },
    { state: '[~]', label: 'in Arbeit' },
    { state: '[x]', label: 'erledigt' },
    { state: '[!]', label: 'blockiert' },
  ],
  anchors: [
    { key: 'LINK_CHECK', meaning: 'Relative Links gültig?' },
    { key: 'CHANGED_FILES', meaning: 'Geänderte Dateien' },
    { key: 'WORK_ITEM', meaning: 'work/ + WRK-Eintrag' },
    { key: 'VERDICT', meaning: 'Review-Ergebnis (Verify)' },
    { key: 'FINDINGS', meaning: 'Guardrail-Befunde' },
    { key: 'OPEN_QUESTIONS', meaning: 'Offene Annahmen' },
  ],
  workflows: [
    { when: 'Erstsetup', id: 'bootstrap-adopt', fresh: 'Ja' },
    { when: 'Nächstes Kapitel', id: 'bootstrap-continue', fresh: 'Ja' },
    { when: 'Sektion vertiefen', id: 'refinement', fresh: 'Ja' },
    { when: 'Code geändert', id: 'maintenance-diff-range', fresh: 'Ja' },
    { when: 'Architekturfrage', id: 'architecture-work-query', fresh: 'Ja' },
    { when: 'Nach Sync / Meilenstein', id: 'review-maintenance', fresh: 'Pflicht' },
  ],
  blueprintSections: [
    '## Documentation template — arc42, lean-service, c4-light, adr-first',
    '## Status — Phase · Sektion · Datei · [ ]/[~]/[x]/[!]',
    '## Work register — WRK-NNN · Track · Type · Status',
    '## Reviews — PASS · PASS WITH NOTES · FAIL',
    '## Guardrail findings — Smells, Abweichungen',
    '## Session log — Entscheidungen, Resume-Prompt',
  ],
  humanDuties: [
    'Phasen freigeben vor [x]',
    'Verify in frischem Chat — nie im Schreib-Chat',
    'Docs im selben PR wie Architektur-Code',
    'Ein Schreib-Agent pro Graph gleichzeitig',
    'Keine Secrets in Prompts — Diffs redigieren',
  ],
  limits: [
    'Halluzinationen — Graph reduziert, Mensch validiert',
    'Kein Live-Produktionszustand — statische Docs ≠ Metriken',
    'Org-Ownership nötig — sonst verrottet der Graph',
    'Parallele Agenten auf demselben Graph — vermeiden',
  ],
  templates: ['arc42 (Standard, Multi-Modul)', 'lean-service (ein Service)', 'c4-light', 'adr-first'],
  mechanisms: ['Documentation API', 'MCP Transport', 'Session-Disziplin'],
  footer: 'X-BE · Architecture Graph Method · AGM',
  sourceUrl: 'https://github.com/abx-git/agm',
} as const;
